-- Schema base para Prode Mundial v3.
-- Supabase Auth maneja auth.users; estas tablas pertenecen a la app.

create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    email text not null,
    display_name text,
    is_admin boolean not null default false,
    created_at timestamptz not null default now()
);

create table if not exists public.teams (
    id bigint generated by default as identity primary key,
    name text not null,
    code text not null unique,
    url_flag text
);

create table if not exists public.groups (
    id bigint generated by default as identity primary key,
    name text not null unique
);

create table if not exists public.matches (
    id bigint generated by default as identity primary key,
    match_date timestamptz not null,
    stage text not null,
    group_id bigint references public.groups(id),
    home_team_id bigint not null references public.teams(id),
    away_team_id bigint not null references public.teams(id),
    home_score integer,
    away_score integer,
    is_finished boolean not null default false,
    created_at timestamptz not null default now(),
    check (home_score is null or home_score >= 0),
    check (away_score is null or away_score >= 0)
);

create table if not exists public.predictions (
    id bigint generated by default as identity primary key,
    user_id uuid not null references public.profiles(id) on delete cascade,
    match_id bigint not null references public.matches(id) on delete cascade,
    home_score integer not null,
    away_score integer not null,
    points integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (user_id, match_id),
    check (home_score >= 0),
    check (away_score >= 0),
    check (points >= 0)
);

create table if not exists public.prode_groups (
    id bigint generated by default as identity primary key,
    name text not null unique,
    password_hash text not null,
    created_by uuid not null references public.profiles(id) on delete cascade,
    created_at timestamptz not null default now()
);

create table if not exists public.prode_group_members (
    id bigint generated by default as identity primary key,
    group_id bigint not null references public.prode_groups(id) on delete cascade,
    user_id uuid not null references public.profiles(id) on delete cascade,
    joined_at timestamptz not null default now(),
    unique (group_id, user_id)
);

create index if not exists idx_matches_match_date on public.matches(match_date);
create index if not exists idx_predictions_user_id on public.predictions(user_id);
create index if not exists idx_predictions_match_id on public.predictions(match_id);
create index if not exists idx_group_members_user_id on public.prode_group_members(user_id);
